theme: jekyll-theme-cayman
title: Spectrogram Inpainting for Interactive Generation of Instrument Sounds
description: "Companion website for the eponymous paper published at the 2020 Joint Conference on AI Music Creativity"
github: [metadata]

markdown: kramdown
kramdown:
    math_engine: katex

plugins:
    - jemoji
